server:
  port: ${SERVER_PORT:8080}
api:
  prefix: ${API_PREFIX:/api/v1}
spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/ecommerce?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
    driver-class-name: ${DB_DRIVER:com.mysql.cj.jdbc.Driver}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      format_sql: true
  cache:
    type: redis
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
  flyway:
    locations: classpath:/db/migration,classpath:/dev/db/migration
    baseline-on-migrate: true
    baseline-version: 0
  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE:10MB}
      max-request-size: ${MAX_REQUEST_SIZE:10MB}
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: ${GOOGLE_REDIRECT_URI}
          facebook:
            client-id: ${FACEBOOK_CLIENT_ID}
            client-secret: ${FACEBOOK_CLIENT_SECRET}
            redirect-uri: ${FACEBOOK_REDIRECT_URI}
            scope:
              - email
              - public_profile

api-base-url: ${BASE_URL:http://localhost:8080}
uploads:
  dir: ${UPLOAD_DIR:uploads}
jwt:
  expiration-access-token: ${JWT_EXPIRATION_ACCESS_TOKEN:2592000}
  expiration-refresh-token: ${JWT_EXPIRATION_REFRESH_TOKEN:5184000}
  secret-key: ${JWT_SECRET_KEY}

vnpay:
  tmn-code: ${VNPAY_TMN_CODE}
  hash-secret: ${VNPAY_HASH_SECRET}
  payment-url: ${VNPAY_PAYMENT_URL}
  client-redirect-uri: ${VNPAY_RETURN_URL}
  server-webhook-uri: ${VNPAY_IPN_URL}
  api-url: ${VNPAY_API_URL}
app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:5173}