server:
  port: 8080
api:
  prefix: ${API_PREFIX:/api/v1}
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      format_sql: true
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  flyway:
    locations: classpath:/db/migration,classpath:/dev/db/migration
    baseline-on-migrate: true
    baseline-version: 0
  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE:10MB}
      max-request-size: ${MAX_REQUEST_SIZE:10MB}
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: http://localhost:5173/auth/google/callback
          facebook:
            client-id: ${FACEBOOK_CLIENT_ID}
            client-secret: ${FACEBOOK_CLIENT_SECRET}
            redirect-uri: http://localhost:5173/auth/facebook/callback
            scope:
              - email
              - public_profile

api-base-url: http://localhost:8080
uploads:
  dir: uploads
jwt:
  expiration-access-token: ${JWT_EXPIRATION_ACCESS_TOKEN:2592000}
  expiration-refresh-token: ${JWT_EXPIRATION_REFRESH_TOKEN:5184000}
  secret-key: ${JWT_SECRET_KEY}
vnpay:
  tmn-code: ${VNPAY_TMN_CODE}
  hash-secret: ${VNPAY_HASH_SECRET}
  payment-url: ${VNPAY_PAYMENT_URL}
  client-redirect-uri: http://localhost:5173/payment-result
  server-webhook-uri: http://localhost:8080/api/v1/payments/vnpay/ipn
  api-url: ${VNPAY_API_URL}
app:
  cors:
    allowed-origins: http://localhost:5173





